---
language: java

matrix:
  fast_finish: true
  include:
    - jdk: openjdk7
      env: MAIN_ARGS="test"
    - jdk: oraclejdk7
      env: MAIN_ARGS="test" COVERALLS_ARGS="mvn clean cobertura:cobertura coveralls:report"

script:
  - mvn clean $MAIN_ARGS

after_success:
  - $COVERALLS_ARGS
